### ISSUE TITLE
Assert while archiving

### ISSUE THREAD

**Issue by ihdavids** [ihdavids/orgextended#15]
The node had some unicode in it. Archiving it seems to cause an exception:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/Users/idavids/Library/Application Support/Sublime Text/Installed Packages/OrgExtended.sublime-package/orgcapture.py", line 259, in run
  File "/Users/idavids/Library/Application Support/Sublime Text/Installed Packages/OrgExtended.sublime-package/orgdb.py", line 79, in Save
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 1418: ordinal not in range(128)

**Comment by ihdavids** [comment]
I think this was fixed with some of the utf-8 work I did recently. 
Closing this for now.
