### ISSUE TITLE
HTML Export Fails

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#18]
1. Create a new org file
2. Put a single item in the org file at line 1. For example `* Blah`
3. Go to Org Export File As Html

This fails with the following traceback 
```
EXPORT STYLE: blocky
EXPORT COMPLETE: C:\Users\Luke\Documents\Org\export.html
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orghtml.py", line 658, in run
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orghtml.py", line 254, in __init__
AttributeError: 'HtmlDoc' object has no attribute 'language'
```

If you add one space at the top, then the html is successfully generated.

**Comment by ihdavids** [comment]
Heh.
Uninitialized field when there is no global content to parse.
I have a fix.

Note the styles I have are just the experiments I had sitting around that are not business specific. In other words... they are pretty terrible. I keep thinking I need to do a version after read the docs or something as the default style. 

Contributing a "decent" style would be amazing... ;)

**Comment by ihdavids** [comment]
1.1.25 May have the fix
