### ISSUE TITLE
Exception during refile

### ISSUE THREAD

**Issue by ihdavids** [ihdavids/orgextended#48]
**Describe the bug**
Crash during refile

**To Reproduce**
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 940, in on_activated
    run_view_callbacks('on_activated', view_id)
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "C:\Users\idavids\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orgextended.py", line 117, in on_activated
    folding.onActivated(view)
  File "C:\Users\idavids\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orgfolding.py", line 127, in onActivated
    fold_all_but_my_tree(view)
  File "C:\Users\idavids\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orgfolding.py", line 60, in fold_all_but_my_tree
    node.unfold(view)
  File "C:\Users\idavids\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orgparse/sublimenode.py", line 128, in unfold
    self.fold_drawers(view)
  File "C:\Users\idavids\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orgparse/sublimenode.py", line 238, in fold_drawers
    if(self.property_drawer_location):
AttributeError: 'OrgRootNode' object has no attribute 'property_drawer_location'
Unable to open //images/groups_here.pngD
decode image failed
reloading /D/Git/doall.ps1
reloading /D/Git/doall.ps1
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "C:\Users\idavids\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orgcapture.py", line 241, in run
AttributeError: 'NoneType' object has no attribute 'FindOrCreateNode'

**Expected behavior**
Should not thrown an exception

**Platform:**
- PC ST4

** Sublime debug console output**
   See above

**Additional context**
This happens on a CANCELLED node with BLOCKED children.

**Comment by ihdavids** [comment]
This is now fixed, closing out
