### ISSUE TITLE
in tables, auto calculating rows sometimes break a column formula

### ISSUE THREAD

**Issue by JosefTaylor** [ihdavids/orgextended#59]
**Describe the bug**
Changing a value in an auto-calculated row can cause formula results to jump between columns

**To Reproduce**
1. Create a table in a .org file
2. Add hashmarks in the leftmost column to mark all rows to auto calculate
3. put some numbers in one column
4. add a column formula to the adjacent (right) column which does something with the numbers
5. edit one of the input cells to be larger by an order of magnitude (add a zero or something on the right)
6. hit tab to re-calculate
7. see error (formula result populates in the input column, next to the input

**Expected behavior**
The formula result should populate in the column targeted by the formula

**Screenshots**
![autocalc-bug](https://user-images.githubusercontent.com/7024203/158181382-997e0075-cbf8-4bb3-9811-1bafcd8f5faa.gif)

**Platform:**
- Eg PC ST3

** Sublime debug console output**
SyntaxError: invalid syntax

OrgExtended.orgtableformula [ERROR]: TABLE ERROR: Traceback (most recent call last):
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 1951, in Execute
    val = self.eval(self.formulas[i].expr)
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\simple_eval.py", line 326, in eval
    return self._eval(ast.parse(expr.strip()).body[0])
  File "./python3.3/ast.py", line 35, in parse
  File "<unknown>", line 1
    remote('thisTable',@ getcolcell(3,0) )
                       ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 2599, in run
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 1834, in HighlightFormula
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 2421, in SingleFormulaIterator
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 1876, in FormulaTargetCellIterator
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 1864, in FormulaTarget
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 2599, in run
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 1834, in HighlightFormula
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 2421, in SingleFormulaIterator
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 1876, in FormulaTargetCellIterator
  File "C:\Users\jtaylor\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgtableformula.py", line 1864, in FormulaTarget
IndexError: list index out of range

**Additional context**

**Comment by ihdavids** [comment]
Thanks, when I get a chance I will try to duplicate.
NOTE: if you have a fix please submit a PR and I will take a look.

**Comment by ihdavids** [comment]
1.2.44 will have a fix for this when I can get it out. 
I was able to duplicate the issue and I believe I understand what was going on.
