### ISSUE TITLE
"org export file to html" fails to install required dependency ?

### ISSUE THREAD

**Issue by berteh** [ihdavids/orgextended#69]
First of all thanks for the great tool. Can you please help me fix the bug below:

**Describe the bug**
Calling **org export file as html** leads to empty (aside from creation timestamp) output and error in console: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed... likely to get dependency `highlightjs`

**To Reproduce**
1. hit ctrl+shift+p for commans box
2. write "org html"
3. click command "org export file as html"
4. See near-empty output file (empty but for html tag, head tag (no content there), and creation timestamp footer) and error in console

**Expected behavior**
html content in output file

**Platform:**
- Ubuntu 20.04.5 LTS

**Sublime debug console output**

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1488, in run_
    return self.run(edit, **args)
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgsourceblock.py", line 1531, in run
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgsourceblock.py", line 1522, in ContinueRun
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/pymitter.py", line 350, in EmitIf
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/pymitter.py", line 303, in emit
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/pymitter.py", line 303, in <listcomp>
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/pymitter.py", line 331, in __call__
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orghtml.py", line 691, in OnDoneSourceBlockExecution
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgexporter.py", line 216, in Run
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgexporter.py", line 179, in BuildHead
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orghtml.py", line 674, in CustomBuildHead
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orghtml.py", line 189, in GetHighlightJsCss
  File "/home/<user>/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgutil/webpull.py", line 33, in download_highlightjs
  File "/home/bertrand/.config/sublime-text/Packages/requests/all/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/<user>/.config/sublime-text/Packages/requests/all/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/<user>/.config/sublime-text/Packages/requests/all/requests/sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/<user>/.config/sublime-text/Packages/requests/all/requests/sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "/home/<user>/.config/sublime-text/Packages/requests/all/requests/adapters.py", line 513, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
```

**Comment by ihdavids** [comment]
Thanks for the call stack. I will take a look.
The exporter does embed highlightjs into the webpage so source blocks can be highlighted.
At one point in time I had an option that wouldn't download but would link, I abandoned that as I actually really liked having a self contained html page. 

Hmmm, I'll see about reviving that and or giving you an option to not use highlightJs as well. You can probably download your own copy of highlight js and avoid the error, but I would need to take a bit to figure out where it needs to go again. (Into your Packages/User folder somewhere)  

Thanks again for the bug report. Really nice to have someone using it.

**Comment by ihdavids** [comment]
Interesting, I am getting the certificate failed assert as well when I use it now, so something has probably rusted out in sublime and or highlight JS here.

**Comment by ihdavids** [comment]
If you can work off the non package version (bleeding edge) I have pushed a version that turns off the highlightJs pull and also fixes another break I found while quickly testing that. Should get you able to export without source block color highlighting for now. 

I will work on fixing the highlightjs stuff when I have a moment, also adding an option to just turn it off since not everybody will want that anyways.

**Comment by ihdavids** [comment]
1.2.52 has a fix I hope.

**Comment by berteh** [comment]
confirmed. thanks.
