### ISSUE TITLE
Arm64 arch missing

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ihdavids/orgextended#89]
**Describe the bug**
There's an error in st logs

**To Reproduce**
Just to install a plugin on the given environment.

**Platform:**
- os: macOS 14.5 (23F79)
- ST: 4177

** Sublime debug console output**
```log
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1686, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/OrgExtended.sublime-package/orgrevealjs.py", line 5, in <module>
  File "/Users/user/Library/Application Support/Sublime Text/Lib/python33/regex.py", line 398, in <module>
    import _regex_core
  File "/Users/user/Library/Application Support/Sublime Text/Lib/python33/_regex_core.py", line 21, in <module>
    import _regex
ImportError: dlopen(/Users/user/Library/Application Support/Sublime Text/Lib/python33/_regex.so, 0x0002): tried: '/Users/user/Library/Application Support/Sublime Text/Lib/python33/_regex.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/Library/Application Support/Sublime Text/Lib/python33/_regex.so' (no such file), '/Users/user/Library/Application Support/Sublime Text/Lib/python33/_regex.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64'))
```

**Comment by ihdavids** [comment]
This should be fixed in 1.2.54 which should include an upgrade to python 3.8 
I am running it fine on my M2.
